<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Save</name>
   <tag></tag>
   <elementGuidId>3d036e4b-4590-474b-8a1a-4f4979b5bb42</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[count(. | //*[@id = 'globalquickcreate_save_button_NavBarGloablQuickCreate']) = count(//*[@id = 'globalquickcreate_save_button_NavBarGloablQuickCreate'])][count(. | //*[@class = 'mscrm-globalqc-actionbutton']) = count(//*[@class = 'mscrm-globalqc-actionbutton'])][count(. | //*[@button_quickiframe_id = 'NavBarGloablQuickCreate']) = count(//*[@button_quickiframe_id = 'NavBarGloablQuickCreate'])][count(. | //*[text() = 'Save']) = count(//*[text() = 'Save'])][count(. | id(&quot;globalquickcreate_save_button_NavBarGloablQuickCreate&quot;)) = count(id(&quot;globalquickcreate_save_button_NavBarGloablQuickCreate&quot;))]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='globalquickcreate_save_button_NavBarGloablQuickCreate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>globalquickcreate_save_button_NavBarGloablQuickCreate</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mscrm-globalqc-actionbutton</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>button_quickiframe_id</name>
      <type>Main</type>
      <value>NavBarGloablQuickCreate</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Save</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;globalquickcreate_save_button_NavBarGloablQuickCreate&quot;)</value>
   </webElementProperties>
</WebElementEntity>
