<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_nfl_languageid_i</name>
   <tag></tag>
   <elementGuidId>89bdf5bc-0115-44ec-817e-0a3d8744a1f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//img[count(. | //*[@src = '/_imgs/search_hover.gif']) = count(//*[@src = '/_imgs/search_hover.gif'])][count(. | //*[@id = 'nfl_languageid_i']) = count(//*[@id = 'nfl_languageid_i'])][count(. | //*[@alt = 'Select a value.']) = count(//*[@alt = 'Select a value.'])][count(. | //*[@class = 'ms-crm-InlineLookupEdit']) = count(//*[@class = 'ms-crm-InlineLookupEdit'])][count(. | //*[@title = 'Select a value.']) = count(//*[@title = 'Select a value.'])][count(. | id(&quot;nfl_languageid_i&quot;)) = count(id(&quot;nfl_languageid_i&quot;))][count(. | //*[@ref_element = 'Object Repository/Page_Player Language New Player Lan/iframe_NavBarGloablQuickCreate']) = count(//*[@ref_element = 'Object Repository/Page_Player Language New Player Lan/iframe_NavBarGloablQuickCreate'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/_imgs/search_hover.gif</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nfl_languageid_i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Select a value.</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ms-crm-InlineLookupEdit</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Select a value.</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nfl_languageid_i&quot;)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Player Language New Player Lan/iframe_NavBarGloablQuickCreate</value>
   </webElementProperties>
</WebElementEntity>
